CREATE TABLE IF NOT EXISTS `specimen_types` (
    `code` VARCHAR(2) CHARACTER SET utf8,
    `english` VARCHAR(40) CHARACTER SET utf8
);
INSERT INTO `specimen_types` VALUES ('no','Nose'),
	('th','Throat'),
	('sp','Sputum'),
	('br','Bronchial'),
	('ea','Ear'),
	('ey','Eyes'),
	('mo','Mouth'),
	('sk','Skin'),
	('jt','Joint'),
	('uc','Urine, catheter'),
	('ur','Urine'),
	('bl','Blood'),
	('sf','Cerebrospinal fluid'),
	('lu','Lung'),
	('ab','Abdominal fluid'),
	('ga','Gastric fluid'),
	('dr','Drainage'),
	('fl','Fluid'),
	('bi','Bile'),
	('wd','Wound'),
	('sw','Wound, surgical'),
	('as','Abscess'),
	('ps','Pus'),
	('am','Amniotic fluid'),
	('tr','Tracheal'),
	('si','Sinus'),
	('sb','Swab'),
	('at','Aspirate'),
	('fn','Aspirate, fine-needle'),
	('og','Organ'),
	('cx','Cervix'),
	('um','Umbilical cord'),
	('va','Vagina'),
	('bx','Biopsy'),
	('ti','Tissue'),
	('bn','Brain'),
	('he','Heart'),
	('hv','Heart valve'),
	('li','Liver'),
	('st','Stool'),
	('re','Rectal'),
	('mu','Muscle'),
	('ha','Hand'),
	('ar','Arm'),
	('ax','Axilla'),
	('co','Conjunctiva'),
	('em','Ear, middle'),
	('eo','Ear, outer'),
	('fi','Fistula'),
	('gn','Genital'),
	('gm','Genital, male'),
	('gf','Genital, female'),
	('pl','Placenta'),
	('bt','Breast'),
	('mi','Breast milk'),
	('sm','Semen'),
	('ue','Urethra'),
	('cv','Urine, clean-voided'),
	('se','Secretion'),
	('bo','Bone'),
	('bm','Bone marrow'),
	('ba','Broncho-alveolar lavage'),
	('pf','Pleural fluid'),
	('rl','Respiratory, lower'),
	('ru','Respiratory, upper'),
	('ta','Tracheal aspirate'),
	('ux','Ulcer, external'),
	('ui','Ulcer, internal'),
	('sc','Screening'),
	('mr','Screen for MRSA'),
	('vr','Screen for VRE'),
	('rs','Research'),
	('la','Laboratory'),
	('ex','Quality control, external'),
	('rp','Respiratory'),
	('ul','Ulcer'),
	('ub','Urine, bladder'),
	('uk','Urine, kidney'),
	('ua','Urine, suprapubic aspirate'),
	('ki','Kidney'),
	('ut','Uterus'),
	('du','Duodenum'),
	('me','Mediastinum'),
	('bu','Bursa'),
	('cy','Cyst'),
	('ln','Lymph node'),
	('gl','Gland'),
	('ot','Other'),
	('ca','Catheter'),
	('di','Dialysis fluid'),
	('en','Environmental'),
	('pr','Prosthesis'),
	('cc','Catheter, central'),
	('wa','Water'),
	('fo','Food'),
	('un','Unknown'),
	('qc','Quality control'),
	('hr','Hair'),
	('nl','Nail'),
	('np','Nasopharynx'),
	('ft','Foot'),
	('au','Autopsy'),
	('fb','Foreign body'),
	('mc','Meconium'),
	('iu','Intra-uterine device'),
	('fv','Urine, first-voided'),
	('us','Umbilicus'),
	('is','Isolate'),
	('ad','Abscess, abdominal'),
	('bs','Burns'),
	('cp','Catheter, permanent'),
	('cr','Cornea'),
	('ee','Empyema'),
	('ep','Empyema, pleural'),
	('es','Empyema, subdural'),
	('hp','Heart valve, prosthetic'),
	('mb','Mini-BAL'),
	('pm','Pacemaker'),
	('pn','Pancreas'),
	('pd','Pericardial fluid'),
	('cs','Catheter site'),
	('pb','Prosthesis, bone'),
	('sh','Prosthesis, shunt'),
	('pv','Prosthesis, vascular'),
	('pc','Protected brush catheter'),
	('tn','Tonsils'),
	('ud','Ulcer, decubitis'),
	('uz','Urine, non-catheterized'),
	('uo','Urine, nephrostomy'),
	('uu','Urine, unknown source'),
	('pt','Abscess, peritonsillar'),
	('de','Abscess, dental'),
	('ac','Abscess, perirectal'),
	('ak','Abscess, skin'),
	('ap','Appendix'),
	('ch','Catheter, peripheral'),
	('cm','Culture medium'),
	('cb','Cyst, Bartholin''s'),
	('dn','Drain'),
	('ec','Endocardium'),
	('ed','Epididymis'),
	('eg','Epiglottis'),
	('eh','Esophagus'),
	('fa','Fallopian tube'),
	('fu','Furuncle'),
	('gb','Gallbladder'),
	('hi','Hip'),
	('hf','Hip fluid'),
	('it','Insect'),
	('jf','Joint fluid'),
	('kn','Knee'),
	('kf','Knee fluid'),
	('lx','Larynx'),
	('lp','Lip'),
	('lo','Lochia'),
	('ov','Ovary'),
	('pe','Penis'),
	('pg','Penile discharge'),
	('pi','Perineum'),
	('pa','Plasma'),
	('po','Prostate'),
	('pu','Prostatic fluid'),
	('rc','Rectouterine pouch (Douglas'' cul-de-sac)'),
	('tp','Scotch tape test for parasites'),
	('sr','Serum'),
	('su','Shunt fluid'),
	('sl','Spleen'),
	('sa','Sputum for acid-fast bacilli'),
	('in','Sputum, induced'),
	('sg','String test for parasites'),
	('te','Testes'),
	('to','Tooth'),
	('wo','Worm'),
	('wt','Wound, sternal'),
	('an','Abdomen'),
	('bv','Blood vessel'),
	('hd','Head'),
	('sv','Salivary gland'),
	('lg','Leg'),
	('nk','Neck'),
	('nv','Nerve'),
	('lv','Pelvis'),
	('cd','Screen for C. difficile'),
	('gr','Groin'),
	('ig','Inguinal'),
	('cu','Catheter, umbilical'),
	('fd','Foot, diabetic');
