<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;

class IsolateApiController extends Controller
{
    public function getIsolates()
    {
        $flattenedData = DB::table('isolates')
    ->join('hospitals', 'isolates.hospital_id', '=', 'hospitals.id')
    ->join('site_isolates', 'isolates.id', '=', 'site_isolates.isolate_id')
    ->join('laboratory_isolates', 'isolates.id', '=', 'laboratory_isolates.isolate_id')
    ->select(
        'isolates.id as isolate_id',
        'isolates.patient_id',
        'isolates.created_by as isolate_created_by',
        'isolates.updated_by as isolate_updated_by',
        'hospitals.hospital_name',
        'hospitals.hospital_code',
        'site_isolates.patient_first_name',
        'site_isolates.patient_middle_name',
        'site_isolates.patient_last_name',
        'site_isolates.patient_age',
        'site_isolates.patient_sex',
        'site_isolates.ward',
        'site_isolates.date_of_admission',
        'site_isolates.attending_physician',
        'site_isolates.specimen_type',
        'site_isolates.date_of_sample_collection',
        'site_isolates.date_received_arsrl',
        'site_isolates.bacterial_identification as site_bacterial_identification',
        'site_isolates.esbl as site_esbl',
        'site_isolates.date_of_testing as site_date_of_testing',
        'site_isolates.amk_disk as site_amk_disk',
        'site_isolates.amk_disk_ris as site_amk_disk_ris',
        'site_isolates.amk_mic_operand as site_amk_mic_operand',
        'site_isolates.amk_mic as site_amk_mic',
        'site_isolates.amk_mic_ris as site_amk_mic_ris',
        'site_isolates.amp_disk as site_amp_disk',
        'site_isolates.amp_disk_ris as site_amp_disk_ris',
        'site_isolates.amp_mic_operand as site_amp_mic_operand',
        'site_isolates.amp_mic as site_amp_mic',
        'site_isolates.amp_mic_ris as site_amp_mic_ris',
        'site_isolates.sam_disk as site_sam_disk',
        'site_isolates.sam_disk_ris as site_sam_disk_ris',
        'site_isolates.sam_mic_operand as site_sam_mic_operand',
        'site_isolates.sam_mic as site_sam_mic',
        'site_isolates.sam_mic_ris as site_sam_mic_ris',
        'site_isolates.fox_disk as site_fox_disk',
        'site_isolates.fox_disk_ris as site_fox_disk_ris',
        'site_isolates.fox_mic_operand as site_fox_mic_operand',
        'site_isolates.fox_mic as site_fox_mic',
        'site_isolates.fox_mic_ris as site_fox_mic_ris',
        'site_isolates.cro_disk as site_cro_disk',
        'site_isolates.cro_disk_ris as site_cro_disk_ris',
        'site_isolates.cro_mic_operand as site_cro_mic_operand',
        'site_isolates.cro_mic as site_cro_mic',
        'site_isolates.cro_mic_ris as site_cro_mic_ris',
        'site_isolates.caz_disk as site_caz_disk',
        'site_isolates.caz_disk_ris as site_caz_disk_ris',
        'site_isolates.caz_mic_operand as site_caz_mic_operand',
        'site_isolates.caz_mic as site_caz_mic',
        'site_isolates.caz_mic_ris as site_caz_mic_ris',
        'site_isolates.cip_disk as site_cip_disk',
        'site_isolates.cip_disk_ris as site_cip_disk_ris',
        'site_isolates.cip_mic_operand as site_cip_mic_operand',
        'site_isolates.cip_mic as site_cip_mic',
        'site_isolates.cip_mic_ris as site_cip_mic_ris',
        'site_isolates.chl_disk as site_chl_disk',
        'site_isolates.chl_disk_ris as site_chl_disk_ris',
        'site_isolates.chl_mic_operand as site_chl_mic_operand',
        'site_isolates.chl_mic as site_chl_mic',
        'site_isolates.chl_mic_ris as site_chl_mic_ris',
        'site_isolates.gen_disk as site_gen_disk',
        'site_isolates.gen_disk_ris as site_gen_disk_ris',
        'site_isolates.gen_mic_operand as site_gen_mic_operand',
        'site_isolates.gen_mic as site_gen_mic',
        'site_isolates.gen_mic_ris as site_gen_mic_ris',
        'site_isolates.ipm_disk as site_ipm_disk',
        'site_isolates.ipm_disk_ris as site_ipm_disk_ris',
        'site_isolates.ipm_mic_operand as site_ipm_mic_operand',
        'site_isolates.ipm_mic as site_ipm_mic',
        'site_isolates.ipm_mic_ris as site_ipm_mic_ris',
        'site_isolates.mem_disk as site_mem_disk',
        'site_isolates.mem_disk_ris as site_mem_disk_ris',
        'site_isolates.mem_mic_operand as site_mem_mic_operand',
        'site_isolates.mem_mic as site_mem_mic',
        'site_isolates.mem_mic_ris as site_mem_mic_ris',
        'site_isolates.ctx_disk as site_ctx_disk',
        'site_isolates.ctx_disk_ris as site_ctx_disk_ris',
        'site_isolates.ctx_mic_operand as site_ctx_mic_operand',
        'site_isolates.ctx_mic as site_ctx_mic',
        'site_isolates.ctx_mic_ris as site_ctx_mic_ris',
        'site_isolates.fep_disk as site_fep_disk',
        'site_isolates.fep_disk_ris as site_fep_disk_ris',
        'site_isolates.fep_mic_operand as site_fep_mic_operand',
        'site_isolates.fep_mic as site_fep_mic',
        'site_isolates.fep_mic_ris as site_fep_mic_ris',
        'site_isolates.gen_disk as site_gen_disk',
        'site_isolates.gen_disk_ris as site_gen_disk_ris',
        'site_isolates.gen_mic_operand as site_gen_mic_operand',
        'site_isolates.gen_mic as site_gen_mic',
        'site_isolates.gen_mic_ris as site_gen_mic_ris',
        'site_isolates.tet_disk as site_tet_disk',
        'site_isolates.tet_disk_ris as site_tet_disk_ris',
        'site_isolates.tet_mic_operand as site_tet_mic_operand',
        'site_isolates.tet_mic as site_tet_mic',
        'site_isolates.tet_mic_ris as site_tet_mic_ris',
        'site_isolates.date_released as site_date_released',
        'site_isolates.verified_by as site_verified_by',
        'site_isolates.noted_by as site_noted_by',
        'site_isolates.remarks as site_remarks',
        'laboratory_isolates.bacterial_identification as lab_bacterial_identification',
        'laboratory_isolates.esbl as lab_esbl',
        'laboratory_isolates.date_of_testing as lab_date_of_testing',
        'laboratory_isolates.amk_disk as lab_amk_disk',
        'laboratory_isolates.amk_disk_ris as lab_amk_disk_ris',
        'laboratory_isolates.amk_mic_operand as lab_amk_mic_operand',
        'laboratory_isolates.amk_mic as lab_amk_mic',
        'laboratory_isolates.amk_mic_ris as lab_amk_mic_ris',
        'laboratory_isolates.amp_disk as lab_amp_disk',
        'laboratory_isolates.amp_disk_ris as lab_amp_disk_ris',
        'laboratory_isolates.amp_mic_operand as lab_amp_mic_operand',
        'laboratory_isolates.amp_mic as lab_amp_mic',
        'laboratory_isolates.amp_mic_ris as lab_amp_mic_ris',
        'laboratory_isolates.sam_disk as lab_sam_disk',
        'laboratory_isolates.sam_disk_ris as lab_sam_disk_ris',
        'laboratory_isolates.sam_mic_operand as lab_sam_mic_operand',
        'laboratory_isolates.sam_mic as lab_sam_mic',
        'laboratory_isolates.sam_mic_ris as lab_sam_mic_ris',
        'laboratory_isolates.fox_disk as lab_fox_disk',
        'laboratory_isolates.fox_disk_ris as lab_fox_disk_ris',
        'laboratory_isolates.fox_mic_operand as lab_fox_mic_operand',
        'laboratory_isolates.fox_mic as lab_fox_mic',
        'laboratory_isolates.fox_mic_ris as lab_fox_mic_ris',
        'laboratory_isolates.cro_disk as lab_cro_disk',
        'laboratory_isolates.cro_disk_ris as lab_cro_disk_ris',
        'laboratory_isolates.cro_mic_operand as lab_cro_mic_operand',
        'laboratory_isolates.cro_mic as lab_cro_mic',
        'laboratory_isolates.cro_mic_ris as lab_cro_mic_ris',
        'laboratory_isolates.caz_disk as lab_caz_disk',
        'laboratory_isolates.caz_disk_ris as lab_caz_disk_ris',
        'laboratory_isolates.caz_mic_operand as lab_caz_mic_operand',
        'laboratory_isolates.caz_mic as lab_caz_mic',
        'laboratory_isolates.caz_mic_ris as lab_caz_mic_ris',
        'laboratory_isolates.cip_disk as lab_cip_disk',
        'laboratory_isolates.cip_disk_ris as lab_cip_disk_ris',
        'laboratory_isolates.cip_mic_operand as lab_cip_mic_operand',
        'laboratory_isolates.cip_mic as lab_cip_mic',
        'laboratory_isolates.cip_mic_ris as lab_cip_mic_ris',
        'laboratory_isolates.chl_disk as lab_chl_disk',
        'laboratory_isolates.chl_disk_ris as lab_chl_disk_ris',
        'laboratory_isolates.chl_mic_operand as lab_chl_mic_operand',
        'laboratory_isolates.chl_mic as lab_chl_mic',
        'laboratory_isolates.chl_mic_ris as lab_chl_mic_ris',
        'laboratory_isolates.gen_disk as lab_gen_disk',
        'laboratory_isolates.gen_disk_ris as lab_gen_disk_ris',
        'laboratory_isolates.gen_mic_operand as lab_gen_mic_operand',
        'laboratory_isolates.gen_mic as lab_gen_mic',
        'laboratory_isolates.gen_mic_ris as lab_gen_mic_ris',
        'laboratory_isolates.ipm_disk as lab_ipm_disk',
        'laboratory_isolates.ipm_disk_ris as lab_ipm_disk_ris',
        'laboratory_isolates.ipm_mic_operand as lab_ipm_mic_operand',
        'laboratory_isolates.ipm_mic as lab_ipm_mic',
        'laboratory_isolates.ipm_mic_ris as lab_ipm_mic_ris',
        'laboratory_isolates.mem_disk as lab_mem_disk',
        'laboratory_isolates.mem_disk_ris as lab_mem_disk_ris',
        'laboratory_isolates.mem_mic_operand as lab_mem_mic_operand',
        'laboratory_isolates.mem_mic as lab_mem_mic',
        'laboratory_isolates.mem_mic_ris as lab_mem_mic_ris',
        'laboratory_isolates.ctx_disk as lab_ctx_disk',
        'laboratory_isolates.ctx_disk_ris as lab_ctx_disk_ris',
        'laboratory_isolates.ctx_mic_operand as lab_ctx_mic_operand',
        'laboratory_isolates.ctx_mic as lab_ctx_mic',
        'laboratory_isolates.ctx_mic_ris as lab_ctx_mic_ris',
        'laboratory_isolates.fep_disk as lab_fep_disk',
        'laboratory_isolates.fep_disk_ris as lab_fep_disk_ris',
        'laboratory_isolates.fep_mic_operand as lab_fep_mic_operand',
        'laboratory_isolates.fep_mic as lab_fep_mic',
        'laboratory_isolates.fep_mic_ris as lab_fep_mic_ris',
        'laboratory_isolates.gen_disk as lab_gen_disk',
        'laboratory_isolates.gen_disk_ris as lab_gen_disk_ris',
        'laboratory_isolates.gen_mic_operand as lab_gen_mic_operand',
        'laboratory_isolates.gen_mic as lab_gen_mic',
        'laboratory_isolates.gen_mic_ris as lab_gen_mic_ris',
        'laboratory_isolates.tet_disk as lab_tet_disk',
        'laboratory_isolates.tet_disk_ris as lab_tet_disk_ris',
        'laboratory_isolates.tet_mic_operand as lab_tet_mic_operand',
        'laboratory_isolates.tet_mic as lab_tet_mic',
        'laboratory_isolates.tet_mic_ris as lab_tet_mic_ris',
        'laboratory_isolates.date_released as lab_date_released',
        'laboratory_isolates.verified_by as lab_verified_by',
        'laboratory_isolates.noted_by as lab_noted_by',
        'laboratory_isolates.remarks as lab_remarks'
    )
    ->get();

        return response()->json($flattenedData);
    }
}
